///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String logo = 'assets/images/ali_fouad_logo.png';
  static const String countryIcon = 'assets/images/country_code_icon.png';


}
